### PR TITLE
GitHub Action

### PR DESCRIPTION
**Pull request by DerekRoberts**

### CODE REVIEW

**Comment by ashtonmeuser** [comment]
@DerekRoberts Happy to see this PR pop up! Looks like your pods are constantly restarting and the builds are finally failing. This may be due to using the dev server in OpenShift. Have you been deploying with `react-scripts start` in OS previously?

**Comment by DerekRoberts** [comment]
@ashtonmeuser A lot of the objects, including routes, are adding -client to our ours.  I'll create a standalone mode and provide a PR.  Thanks for the GHAction starter!

**Comment by ashtonmeuser** [comment]
That was intentional but poorly documented. Let me know if you hit any other stumbling blocks. Invaluable information you're giving us!

**Comment by DerekRoberts** [comment]
@ashtonmeuser I've been trying to have a lengthier conversation with you on Rocket.Chat.  Please go there!

**Pull request closed without merging**
