### PR TITLE
Improve Image Promotion

### PR DESCRIPTION
**Pull request by DerekRoberts**
Use separate imagestreams for DEV and PROD.  Revise image promotion accordingly.

### CODE REVIEW

**Comment by Kyubinhan** [comment]
Looks like prod deployment silently failed
https://jenkins-prod-auzhsi-tools.pathfinder.gov.bc.ca/blue/organizations/jenkins/wps-web/detail/PR-91/6/pipeline/25#step-33-log-155

**Comment by DerekRoberts** [comment]
> Let's do the same for api please.

Subtree.  API changes are on the way, so keep an eye out for the PR!

**Comment by DerekRoberts** [comment]
@Kyubinhan Sorry, I clobbered your comment.  Good catch on the timeout/fail!  I'll create an issue.

**Comment by Kyubinhan** [comment]
Looks like prod deployment has silently failed
https://jenkins-prod-auzhsi-tools.pathfinder.gov.bc.ca/blue/organizations/jenkins/wps-web/detail/PR-91/6/pipeline/25#step-33-log-155

**Comment by DerekRoberts** [comment]
> Looks like prod deployment has silently failed
> https://jenkins-prod-auzhsi-tools.pathfinder.gov.bc.ca/blue/organizations/jenkins/wps-web/detail/PR-91/6/pipeline/25#step-33-log-155

@Kyubinhan Good catch and ticket write-up.  Re-run was successful.

**Pull request merged**
