### PR TITLE
Deploy on Merge

### PR DESCRIPTION
**Pull request by DerekRoberts**
This PR has been through a few revisions.  The current action will deploy on merge, defaulting to the TEST project until pointing to master.

### CODE REVIEW

**Comment by bcgov-wps** [comment]
Thanks for the pull request! <br>
Please see [CONTRIBUTING.md](https://github.com/bcgov/wps-web/blob/master/CONTRIBUTING.yaml) \
for details. <br>
IMPORTANT: Make sure any \
[post-merge rollouts](https://github.com/bcgov/wps-web/actions?query=workflow%3A%22Post-merge+Rollout%22) \
complete successfully.

**Comment by bcgov-wps** [comment]
Thanks for the pull request! <br> Please see [CONTRIBUTING.md](https://github.com/bcgov/wps-web/blob/master/CONTRIBUTING.yaml)  for details.

**Comment by bcgov-wps** [comment]
Thanks for the pull request! <br> Please see [CONTRIBUTING.md](https://github.com/bcgov/wps-web/blob/master/CONTRIBUTING.md)  for details.

**Comment by bcgov-wps** [comment]
Thanks for the pull request! <br> Please see [CONTRIBUTING.md](https://github.com/bcgov/wps-web/blob/master/CONTRIBUTING.md)  for details.

**Comment by DerekRoberts** [comment]
Can be reused when/if deploy on merge is adopted.

**Pull request closed without merging**
